- external/FindLibObs.cmake
Avoids this warning in cmake .. on fedora33:
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
The package name passed to `find_package_handle_standard_args` (Libobs)
does not match the name of the calling package (LibObs).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
> Fixed libobs case in FindLibObs.cmake

- CMakeLists.txt
- README.md
- src/Model.h
- src/background-filter.cpp
This commit patches for using the GPU on Linux as detailed in https://github.com/royshil/obs-backgroundremoval/issues/56
Additionally it expands on the installation instructions for Ubuntu.
> Linux GPU Usage

- README.md
The current preferred installation method for macOS from https://github.com/royshil/obs-backgroundremoval/pull/15 is `unzip -o obs-backgroundremoval-macosx.zip -d "/Library/Application Support/obs-studio/plugins"`. This results in files that do not seem to match the expected file hierarchy.
There are instances where faulty macOS install instructions resulted in people trying to fix it manually, to their confusion when it did not work: https://github.com/royshil/obs-backgroundremoval/issues/51
Working file structure (obs-backgroundremoval v0.4.0, OBS v27.1.3):
```console
sh-3.2# find "/Library/Application Support/obs-studio/plugins"
/Library/Application Support/obs-studio/plugins
/Library/Application Support/obs-studio/plugins/obs-backgroundremoval
/Library/Application …
```
> fix macOS /Library installation method

- README.md
This commit adds libsimde-dev to the readme to resolve
```
/usr/include/obs/graphics/../util/sse-intrin.h:24:10: fatal error: simde/x86/sse2.h: No such file or directory
```
> Add libsimde-dev to readme

- .github/workflows/flatpak.yml
- ci/flatpak/com.obsproject.Studio.Plugin.backgroundremoval.metainfo.xml
- ci/flatpak/com.obsproject.Studio.Plugin.backgroundremoval.yaml
- ci/flatpak/flathub.json
I used the files from @tam7t from #67 and added them to a github workflow.
I didn't add any triggers, because right now the workflow will upload the `flatpak` build as an artifact to each run, so I didn't want to clutter your repository with the big artifacts.
But this way it should be reasonably simply to trigger a build every once in a while, so flatpak users can download a plugin they can just install and use.
Or - if nothing else - maybe you can just use this as starting point to create your own better workflow.
Only weird idiosyncrasy I found is that I couldn't use the flatpak bundle feature of the action, as the plugin is a `runtime` not an `app` - that's why I added a step that actually builds the bundle.
> Add a flatpak build workflow to this plugin

- cmake/ObsPluginHelpers.cmake
- src/Model.h
- src/background-filter.cpp
Enables -Werror in linux and mac and /WX in Windows.
The increment in assignment may conclude in undefined behavior.
std::pow is double so they turned into integer operations.
> Enable -Werror and /WX

- cmake/bundle/windows/installer-Windows.iss.in
- installer/installer-Windows.iss.in
according to https://github.com/obsproject/obs-plugintemplate/issues/70 the mywebsite.com url in the windows installer causes a malware threat. on top of being just wrong.
> Remove random url from windows installer causing malware threats

- cmake/BuildMyOpenCV.cmake
Building on Pop_os resulted in an At least one entry of URL is a path (invalid in a list) warning. This seems to be caused by a forgotten newline in this function. I'm no expert at this, so please correct me if I'm wrong, but this change got my build working again.
> Fix Build error

- src/background-filter.cpp
If a user have migrated from an older version of this plugin, old model files may have remained and tf->modelSelection is set not to be prefixed with models. This change aborts the createOrtSession if tf->model is null and it prevents the segmentation fault of executing tf->model->populateInputOutputNames() when tf->model is null.
Fixes #184.
> Abort if tf->model is null in createOrtSession

- src/background-filter.cpp
In the current implementation, feathering the portrait will include the edge of the background and I don't think this is what people expect from the feathering feature.
Adding erosion process before boxFilter will be what people expect.
> Feathering should be done within the contour

- src/background-filter.cpp
Removing the ability to set the background color, it will always be transparent.
This will undo the need for an additional chroma key filter.
closing #193
> Remove BG color, transparent by default

- CMakeLists.txt
Flatpak has CMake 3.25.1.
cmake_minimum_required must be below 3.25.1 for Flatpak.
Building ONNX Runtime requires 3.25.2 but we use pre-built ONNX Runtime for Flatpak so that CMake 3.25.1 is valid only for Flatpak build.
The deb build still requires 3.25.2 and this is great to note on README.md or CONTRIBUTING.md.
> Fix CMakeLists.txt for Flatpak builds

- .github/scripts/.package.zsh
- cmake/bundle/macos/Distribution.xml
- cmake/bundle/macos/scripts/postinstall
The pkg file created by the Packages will require users to do the following steps.
https://github.com/royshil/obs-backgroundremoval/issues/146#issuecomment-1456343517
The pkgbuild and productbuild commands are the newer way to create pkgs and AFAIK pkgs created by these commands won't require users to take the additional steps to install files under the home directory.
> Use pkgbuild and productbuild for .pkg

- .github/workflows/stale.yml
Handling stale issues automatically.
We have to create no-issue-activity label for the bot to check if 14 days passed after the issue was marked as stalled.
If we adopt the stall bot, the criteria of our closing issue would be clear and the closed issue participants would be convinced.
https://github.com/marketplace/actions/close-stale-issues
> Adopt stale bot

- src/background-filter.cpp
The data field in obs_source_frame must belong to the same bzalloc otherwise OBS references invalid memory area.
> Data in obs_source_frame must belong to the same bzalloc memory.

- cmake/bundle/macos/scripts/postinstall
The installer has failed to install when the path of pkg contains any spaces such as `obs-backgroundremoval-0.5.15-macos-arm64 (1).pkg`.
This change escapes spaces properly and fixes the installation problem on Mac.
> Fix escaping on postinstall of Mac pkg

- src/background-filter.cpp
This filter changed the color of the image. This change fixes the filter to keep the color of the image.
Fixes #218
> Use gs_effect_set_texture

- src/background-filter.cpp
This would improve the performance a bit.
> Execute obs_source_skip_video_filter when vider_render has no output

- src/background-filter.cpp
> Do not execute video_tick when disabled to reduce CPU usage

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This pull request makes the following changes to the issue templates:
- Adds tags automatically to new issues. This would make it easier to search for specific types of issues.
- Add a section to `bug_report.md` asking for an OBS log (and crash report, if applicable) to be uploaded
- Formatting and typo fixes.
I have one question about the current bug report template: Why does it ask for a browser version? I think we can remove this field to stop people like me just typing "N/A" or ignoring this field entirely.
> Issue template improvements

- cmake/BuildMyOnnxruntime.cmake
- cmake/onnxruntime-v1.14.1.patch
https://github.com/royshil/obs-backgroundremoval/issues/182
> Use patched onnxruntime for Arch and Fedora build

- src/background-filter.cpp
Try to fix #243 
We have to use obs_filter_get_target to get the output of the previous filter and we have to use obs_source_get_base_width instead of obs_source_get_width
> Respect the output of the previous filter if exists

- scripts/PKGBUILD
Closes #262 
Closes #172
Closes #34
> Fix PKGBUILD

- src/background-filter.cpp
> * [[deprecated]]
> * This export is deprecated.
> * The OrtSessionOptionsAppendExecutionProvider_DML export on the OrtDmlApi should be used instead.
https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/providers/dml/dml_provider_factory.h#L33-L43
> Avoid using DML deprecated API

- data/effects/kawase_blur.effect
- data/effects/mask_alpha_filter.effect
- src/background-filter.cpp
Fixes #271
https://www.intel.com/content/www/us/en/developer/articles/technical/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html#:~:text=%C2%A0%22Kawase%20blur%22%20filter
> Use Kawase Blur

- .github/workflows/main.yml
We always put Seeking Testers label so let's make it default!
> Upload build artifacts by default

- README.md
It is enough for Arch Linux users to mention AUR.
Each Arch user builds an AUR package in their own way.
> Add the link to AUR

- README.md
- docs/BUILDING-OPENSUSE.md
The very helpful openSUSE installation instructions were not referenced or linked from anywhere, so they were easy to miss.
So link to them from the top-level `README.md`.
> Make it easier to spot the openSUSE installation instructions

- README.md
On Ubuntu 20.04, libstdc++ version won't match to the one this plugin expects and fail to load with unfriendly message.
We have to state that only Ubuntu 22.04 or later is supported by our pre-built binaries.
> We have to state that the pre-built binary only works on Ubuntu 22.04 or later

- cmake/ObsPluginHelpers.cmake
This plugin actually needs OBS 28+.
Qt dependencies are built in the main OBS package so I want to omit them.
> Require OBS 28+ on the deb package

- cmake/FetchOnnxruntime.cmake
> Fix to include libonnxruntime.1.15.1

- buildspec.json
- cmake/common/buildspec_common.cmake
I finally finally concluded that we have to use OBS 29 with the new build system and Qt6.
It is nearly impossible to build both with Qt6 and with OBS 28.
See https://github.com/royshil/obs-backgroundremoval/pull/359
I think our plugin may work with OBS 28 when the build dependency is OBS 29.
> We need to update the OBS dependency to 29.

- CMakeLists.txt
- CMakePresets.json
- src/plugin-main.c
- src/update-checker/UpdateDialog.cpp
- src/update-checker/UpdateDialog.hpp
- src/update-checker/update-checker.cpp
- src/update-checker/update-checker.h
> An update dialog skelton

- CMakeLists.txt
- src/background-filter.cpp
We decided to use libcurl and not to use QtNetwork so I want to remove QtNetwork from this plugin.
> Remove QtNetwork

- data/config.json
- src/plugin-main.c
- src/update-checker/UpdateDialog.cpp
- src/update-checker/UpdateDialog.hpp
- src/update-checker/github-utils.cpp
- src/update-checker/github-utils.h
- src/update-checker/update-checker.cpp
- src/update-checker/update-checker.h
Implementing the version check and update dialog including the "opt out" option for update checks
towards #352
> Update version check and dialog

- .github/scripts/.package.zsh
It was revealed that the modification of package-macos is not reflected and the modification was left broken.
This PR is intended to fix the modification of the packaging process.
> Fix to use pkgbuild properly

- .gitignore
Just a suggestion - the `docs`directory is currently being ignored by git, making it hard to make changes.
Maybe remove it from exclusion? :smile: 
(It has been like this since [the commit on June 29th](https://github.com/royshil/obs-backgroundremoval/commit/c9d86548bc752b0eb157d47fd543598d05e712a2#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947))
> Don't ignore the docs directory

- cmake/common/compiler_common.cmake
I have a build issue on openSUSE Leap 15.5 that its build system does not support C17.
The CMake provided by openSUSE Leap 15.5 is 3.20 and this version does not understand C17.
https://cmake.org/cmake/help/latest/prop_tgt/C_STANDARD.html
This PR will fix the build on openSUSE Leap.
> C17 is only supported CMake 3.21+

- src/update-checker/CurlClient/CMakeLists.txt
- src/update-checker/URLSessionClient/CMakeLists.txt
- src/update-checker/WinRTHttpClient/CMakeLists.txt
This change is needed to build on openSUSE Leap
> Generate static libraries for HttpClient

- docs/BUILDING-FEDORA.md
`curl-devel` is needed on fedora38
> BUILDING-FEDORA.md: add curl-devel

- CMakePresets.json
The cache variable USE_SYSTEM_CURL is no longer used.
This PR removes this cache variable from CMakePresets.json
> Remove USE_SYSTEM_CURL

- buildspec.json
We no longer use the Packages.app to create pkg on Mac.
The hash of Packages.app is changed and it causes the build failure so that I want to remove the Packages.app.
> Remove the Packages.app

- src/background-filter.cpp
- src/enhance-filter.cpp
- src/models/Model.h
- src/obs-utils/obs-config-utils.cpp
- src/ort-utils/ort-session-utils.cpp
- src/ort-utils/ort-session-utils.h
- src/plugin-support.c.in
- src/plugin-support.h
- src/update-checker/github-utils.cpp
While this is not a formal fix for the bug, it adds robustness and better logging
> Handle model load bug

- cmake/FetchOpenCV.cmake
Since we moved the OpenCV repository, we need to fix the URL of it.
> Fix OpenCV binary URL

- cmake/FetchOnnxruntime.cmake
Onnxruntime_VERSION is needed when custom tarball is used
> Fix Flatpak build

- CMakeLists.txt
The fetched onnx has been updated to 1.16.3 in https://github.com/occ-ai/obs-backgroundremoval/commit/1d51cdc420a2a2e1f00fdf47d01b60a4f2af8a8d but not for the system one `USE_SYSTEM_ONNXRUNTIME`
> Update required onnx runtime version

- cmake/FetchOnnxruntime.cmake
- src/ort-utils/ort-session-utils.cpp
Closes #523 
```
cmake . -B build_x86_64 \
-DQT_VERSION=6 \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_POSITION_INDEPENDENT_CODE=ON \
-DENABLE_FRONTEND_API=ON \
-DENABLE_QT=ON \
-DUSE_SYSTEM_ONNXRUNTIME=ON \
-DDISABLE_ONNXRUNTIME_GPU=ON
```
> Add a flag to build without GPU support on Linux

- src/FilterData.h
- src/background-filter.cpp
- src/ort-utils/ort-session-utils.cpp
Closes #525 
Given `std::string s`, `s.c_str()` will be released when `s` is released. If you want to use `s.c_str()` later, you have to hold `s` until you use `s.c_str()`.
On Windows, char paths are stored as multi-byte characters which Windows defines and it is hard to manipulate them with C++ standard libraries (codecvt was deprecated in C++17) so I propose to convert multi-byte characters with Windows-specific API that is guaranteed to work with multi-byte characters on Windows.
> Improve the handling of path string

- README.md
Closes #533 
We provide the FlatPak distribution of our plugin for distributions other than Ubuntu, and they include Debian. However, many users misunderstand that the deb package is for Debian users, and the issues they report consume our time in a void.
To avoid inefficient communication, I suppose we should state that we only support FlatPak installation on Debian.
> Add documentation for Debian users

- src/obs-utils/obs-config-utils.cpp
Thanks for your work on this module.
I noticed the module makes obs crash when the config folder has non-ansi chars on it.
So, I'm proposing this small change, that makes the folder creation similar to modules that run successfully.
> fix create_config_folder not compatible with non-ansi paths

- docs/BUILDING-FEDORA.md
Since Fedora 41, `dnf` 5 is being delivered and the command for installing the `development-tools` has changed.
> doc(fedora): Update `development-tools` install command

- cmake/FetchOnnxruntime.cmake
Introduced a new variable so that built libraries appropriately reflect the custom onnxruntime version.
Also added a symlink from libonxruntime.so.1
The real benefit of this is seen when leveraging CMakeUserPresets as shown in [my gist here](https://gist.github.com/fritz-fritz/b8dd3cc081325d1a73e86be727edc0f7) that addresses #591.
This pull request does not update the default onnxruntime versions or integrate with the installer scripts.
> fix custom onnxruntime version
