CMakeLists.txt
scripts/PKGBUILD

Pull request which fixes items outlined in Issue #16

Arch tuneups

---

scripts/.gitignore
src/background-filter.cpp

what we've been discussing in the aptly-numbered #27

(rough) use CUDA

---

cmake/BuildMyOnnxruntime.cmake

The Linux build is broken due to a linking order issue.
This PR will fix the linking order in Ort.

Fix linux build

---

src/background-filter.cpp

Make obs-backgroundremoval effect filter

---

src/background-filter.cpp

Branch was pushed on royshil's repo from https://github.com/royshil/obs-backgroundremoval/pull/190
TODO: implement feather, configuration
Possible solution for https://github.com/royshil/obs-backgroundremoval/issues/101

Background removal without Chrome Key filter

---

.github/workflows/main.yml
src/background-filter.cpp

Bug reported (verified) from #215

Fix feather + background blur bug

---

src/background-filter.cpp

https://github.com/royshil/obs-backgroundremoval/pull/220#discussion_r1151288952

Reuse texrender and stagesurface

---

src/background-filter.cpp

isDisabled is false when the filter is added.
It seems that activate is not called when the filter is added

Enable this filter when it is added to the source

---

src/background-filter.cpp
src/models/ModelMediapipe.h
src/models/ModelPPHumanSeg.h

I've made a couple small changes that offer a speedup / runtime efficiency to reduce resources

Some speedups

---

CMakeLists.txt
buildspec.json

as we're gearing up for another release, bumping the ver in the build files

Bump version 0.5.17

---

cmake/ObsPluginHelpers.cmake

https://developer.apple.com/forums/thread/115657

Fix notarization errors

---

cmake/BuildMyOpenCV.cmake

```
sudo zypper ar -cfp 90 http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/ packman
sudo zypper dup --from packman --allow-vendor-change
sudo zypper in obs-studio
sudo zypper install -t pattern devel_basis
sudo zypper install zsh cmake Mesa-libGL-devel \
ffmpeg-6-libavcodes-devel ffmpeg-6-libavdevice-devel ffmpeg-6-libavformat-devel \
libcurl-devel Mesa-libEGL-devel \
libpulse-devel libxkbcommon-devel
.github/scripts/build-linux.zsh --skip-deps
```

Fix openSUSE build

---

cmake/FetchOnnxruntime.cmake

#272
https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html

Update DireclML to 1.10.1

---

.github/workflows/main.yml

Have ccache not to create too many caches.

Fix ccache

---

CMakeLists.txt
buildspec.json
data/effects/blend_images.effect
src/enhance-filter.cpp

Adding the GPU selection options, as well as adding high pass filter to enhancement output which is blurry (because the networks run on a lower resolution).

Add GPU to enhance filter

---

cmake/FetchOnnxruntime.cmake

Update ONNX Runtime to v1.15.1

---

.github/actions/package-plugin/action.yaml
.github/workflows/build-project.yaml

This is an upstream issue.
https://github.com/obsproject/obs-plugintemplate/pull/83

Fix releasing for macOS

---

CMakeLists.txt
buildspec.json
src/obs-utils/obs-config-utils.cpp
src/obs-utils/obs-config-utils.h
src/plugin-main.c
src/update-checker/UpdateDialog.cpp
src/update-checker/UpdateDialog.hpp
src/update-checker/github-utils.cpp
src/update-checker/github-utils.h
src/update-checker/update-checker.cpp
src/update-checker/update-checker.h

Adding the changelog to the "new update" dialog
Bumping to v1.1.0

Add change log to update dialog + Bump v1.1.0

---

.github/scripts/utils.zsh/setup_linux

We need to take the upstream change.
https://github.com/obsproject/obs-plugintemplate/commit/13c6bbbaafcfef9547fdf926a1389f519126be70

Install obs-studio from ppa

---

CMakePresets.json

Fix Fedora build

---

.github/scripts/utils.zsh/setup_linux
CMakePresets.json

Use system curl on Linux by default

---

data/effects/kawase_blur.effect
data/effects/mask_alpha_filter.effect

Fixing the halo effect when blurring background by implementing mask-ware Kawase blur

Fix blur background halo effect

---

cmake/FetchOpenCV.cmake

I forgot to link zlib with OpenCV.

Link zlib with OpenCV

---

.github/scripts/.package.zsh

This change will fix the macOS build on main.

Remove check_packages

---

src/update-checker/update-checker.cpp

Prevent OBS crashing with Qt5

---

README.md

The link on the OBS forum would also be great to be replaced with this link.

Replace the download link with the site

---

.github/scripts/.package.zsh
cmake/macos/resources/Distribution.xml.in
cmake/macos/resources/create-package.cmake.in

Distribution.xml should be auto-generated with CMake variables.

Auto-generate Distribution.xml

---

.github/workflows/pages.yaml

The page workflow needs to be run after a release.

Add triggers for the pages workflow

---

cmake/windows/resources/installer-Windows.iss.in

Add metadata to suppress SmartScreen on Windows

---

cmake/windows/resources/installer-Windows.iss.in

Disable program group page in Windows installer

---

CMakeLists.txt
cmake/FetchOnnxruntime.cmake

https://github.com/occ-ai/obs-backgroundremoval/commit/ddf6df0c9957e5c38e14108f48cda95d26e632e7#r137158591

Fix DISABLE_ONNXRUNTIME_GPU to work with USE_SYSTEM_ONNXRUNTIME

---

.github/workflows/build-project.yaml

This will fix the build problem

Fix to use upload-artifact@v4
